/**
 * Imports the game catalog from lauraevan/greatestgreatest-revive into
 * src/data/games.json.
 *
 * The upstream catalog is a `window.GAME_DATA` array of
 * `[source, launchPath, iconPath, displayName, opensDirectly?]`. Icons and the
 * library's launcher pages stay on GitHub and are served through jsDelivr
 * rather than copied here — the two directories come to ~150 MB, and pointing
 * at the source repository means the catalog updates when it does.
 *
 * Usage:
 *   node scripts/import-games.mjs [path-to-clone]
 *
 * With no path it clones the repository into a temporary directory.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "src/data/games.json");

const REPO = "https://github.com/lauraevan/greatestgreatest-revive";
/** jsDelivr serves any public GitHub repository with correct content types. */
const CDN = "https://cdn.jsdelivr.net/gh/lauraevan/greatestgreatest-revive@main";

let clone = process.argv[2];
let temporary = null;

if (!clone) {
  temporary = mkdtempSync(resolve(tmpdir(), "games-"));
  console.log(`Cloning ${REPO} …`);
  execFileSync("git", ["clone", "--depth", "1", REPO, temporary], {
    stdio: "inherit",
    env: { ...process.env, GIT_LFS_SKIP_SMUDGE: "1" },
  });
  clone = temporary;
}

const catalogPath = resolve(clone, "games-data.js");
if (!existsSync(catalogPath)) {
  throw new Error(`No games-data.js in ${clone}`);
}

// The catalog assigns to `window.GAME_DATA`, so give it a window to assign to.
const sandbox = { window: {} };
new Function("window", readFileSync(catalogPath, "utf8")).call(sandbox, sandbox.window);
const raw = sandbox.window.GAME_DATA;

if (!Array.isArray(raw)) throw new Error("games-data.js did not define window.GAME_DATA");

const slug = (value) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "") || "game";

const seen = new Set();
const games = [];
let skipped = 0;

for (const entry of raw) {
  if (!Array.isArray(entry) || entry.length < 4) {
    skipped += 1;
    continue;
  }

  const [source, launchPath, iconPath, name] = entry;
  if (typeof launchPath !== "string" || typeof name !== "string" || !name.trim()) {
    skipped += 1;
    continue;
  }

  // Upstream marks the request-a-game form with bracketed placeholders.
  const title = name.replace(/^\[+|\]+$/g, "").trim();
  if (!title) {
    skipped += 1;
    continue;
  }

  let id = slug(title);
  let suffix = 2;
  while (seen.has(id)) id = `${slug(title)}-${suffix++}`;
  seen.add(id);

  const url = /^https?:/i.test(launchPath)
    ? launchPath
    : `${CDN}/${launchPath.replace(/^\/+/, "")}`;

  const icon =
    typeof iconPath === "string" && iconPath.trim()
      ? /^https?:/i.test(iconPath)
        ? iconPath
        : `${CDN}/${iconPath.replace(/^\/+/, "")}`
      : null;

  games.push({
    id,
    title,
    source: typeof source === "string" && source.trim() ? source.trim() : "Other",
    url,
    icon,
  });
}

games.sort(
  (a, b) => a.source.localeCompare(b.source) || a.title.localeCompare(b.title, "en"),
);

/** "Original" is the hand-picked collection, so it leads. */
const sources = [...new Set(games.map((game) => game.source))].sort((a, b) => {
  if (a === "Original") return -1;
  if (b === "Original") return 1;
  return a.localeCompare(b);
});

const payload = {
  $comment:
    "Auto-generated by scripts/import-games.mjs from lauraevan/greatestgreatest-revive. Do not edit by hand.",
  repository: REPO,
  cdn: CDN,
  importedAt: new Date().toISOString().slice(0, 10),
  sources,
  games,
};

writeFileSync(OUT, `${JSON.stringify(payload, null, 0)}\n`, "utf8");

if (temporary) rmSync(temporary, { recursive: true, force: true });

console.log(`Imported ${games.length} games across ${sources.length} sources.`);
if (skipped) console.log(`Skipped ${skipped} malformed entries.`);
console.log(`Wrote ${OUT} (${(JSON.stringify(payload).length / 1024).toFixed(0)} KB).`);
